import React,{useCallback,useEffect,useState} from 'react';
import {View,Text,ScrollView,TouchableOpacity,TextInput,Image,RefreshControl,KeyboardAvoidingView,Platform,Linking} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {API_URL,userStore} from '../utils/userStore';
export default function ForoScreen({navigation}:any){
 const [tab,setTab]=useState('Programa'),[data,setData]=useState<any>(null),[perfil,setPerfil]=useState<any>(null),[fotos,setFotos]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const cargar=useCallback(async()=>{setBusy(true);try{
   const responses=await Promise.all(['foro/contenido','foro/perfil','galeria?limit=200'].map(p=>fetch(API_URL+'/'+p)));
   if(responses.some(r=>r.status===401||r.status===403)){await userStore.clear();navigation.replace('Login');return;}
   if(responses.some(r=>!r.ok))throw new Error('No se pudo cargar el contenido.');
   const [d,p,f]=await Promise.all(responses.map(r=>r.json()));setData(d);setPerfil(p);setFotos(f);setError('');
 }catch(e:any){setError(e.message||'Error de conexión.');}finally{setBusy(false);}},[navigation]);
 useEffect(()=>{void cargar();},[cargar]);
 async function guardar(){setBusy(true);try{const res=await fetch(API_URL+'/foro/perfil',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(perfil)});const p=await res.json();if(!res.ok)throw new Error(p.message);setPerfil(p);setError('Perfil guardado.');}catch(e:any){setError(e.message||'No se pudo guardar.');}finally{setBusy(false);}}
 return <SafeAreaView style={{flex:1,backgroundColor:'#f8fafc'}}><View style={{padding:16}}><Text style={{color:'#449D3A',fontWeight:'700'}}>Participante del foro</Text><Text style={{fontSize:22,fontWeight:'800'}}>{data?.evento?.nombre||'Foro'}</Text><TouchableOpacity onPress={async()=>{await userStore.clear();navigation.replace('Login');}} style={{paddingVertical:12}}><Text>Cerrar sesión</Text></TouchableOpacity><ScrollView horizontal showsHorizontalScrollIndicator={false}>{['Programa','Noticias','Galería','Mi perfil'].map(t=><TouchableOpacity key={t} onPress={()=>setTab(t)} style={{padding:12,marginRight:6,borderRadius:12,backgroundColor:tab===t?'#449D3A':'#e5e7eb'}}><Text style={{color:tab===t?'#fff':'#111827'}}>{t}</Text></TouchableOpacity>)}</ScrollView></View>
 <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':'height'} style={{flex:1}}><ScrollView automaticallyAdjustKeyboardInsets keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:16,paddingBottom:40}} refreshControl={<RefreshControl refreshing={busy} onRefresh={cargar}/>}>
 {!!error&&<Text style={{marginBottom:14}}>{error}</Text>}
 {tab==='Programa'&&<><Text style={{marginBottom:14}}>{data?.evento?.sobreElEvento}</Text>{data?.actividades?.length===0&&<Text>Pronto publicaremos el programa.</Text>}{data?.actividades?.map((a:any)=><View key={a.id} style={{backgroundColor:'#fff',padding:16,borderRadius:16,marginBottom:12}}><Text style={{fontWeight:'800',fontSize:18}}>{a.nombreActividad}</Text><Text style={{color:'#166534',marginVertical:8}}>{a.fechaActividad?.slice(0,10)} · {a.horaInicioActividad?.slice(11,16)} · {a.nombreSalaEspacio} · {a.estadoEnVivo}</Text><Text>{a.descripcionActividad}</Text>{!!a.notaEnVivo&&<Text style={{fontWeight:'700',marginTop:8}}>{a.notaEnVivo}</Text>}{a.linkReunionVirtual?.startsWith('https://')&&<TouchableOpacity onPress={()=>Linking.openURL(a.linkReunionVirtual)} style={{paddingVertical:12}}><Text style={{color:'#166534'}}>Acceder a la actividad</Text></TouchableOpacity>}</View>)}</>}
 {tab==='Noticias'&&<>{data?.noticias?.length===0&&<Text>No hay noticias publicadas.</Text>}{data?.noticias?.map((n:any)=><View key={n.id} style={{backgroundColor:'#fff',padding:16,borderRadius:16,marginBottom:12}}><Text style={{fontWeight:'800',fontSize:18}}>{n.tituloNoticia}</Text><Text style={{marginTop:10}}>{n.contenidoNoticia}</Text></View>)}</>}
 {tab==='Galería'&&<>{fotos.length===0&&<Text>No hay fotos todavía.</Text>}{fotos.map(f=><View key={f.id} style={{marginBottom:16}}><Image source={{uri:f.urlFoto}} accessibilityLabel={f.descripcion||'Foto del evento'} style={{height:250,width:'100%',resizeMode:'contain'}}/><Text>{f.descripcion||f.autorNombre}</Text></View>)}</>}
 {tab==='Mi perfil'&&perfil&&<><Text>{perfil.correo}</Text>{([['nombres','Nombres',105],['apellidoPaterno','Apellido',65],['telefono','Teléfono',45]] as const).map(([key,label,max])=><View key={key} style={{marginVertical:10}}><Text>{label}</Text><TextInput accessibilityLabel={label} value={perfil[key]||''} maxLength={max} onChangeText={v=>setPerfil({...perfil,[key]:v})} style={{borderWidth:1,borderColor:'#d1d5db',borderRadius:12,padding:12,marginTop:6,fontSize:16}}/></View>)}<TouchableOpacity disabled={busy} onPress={guardar} style={{padding:16,backgroundColor:'#449D3A',borderRadius:12}}><Text style={{color:'#fff',textAlign:'center'}}>Guardar perfil</Text></TouchableOpacity></>}
 </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
