import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Modal, Platform, ScrollView, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Check, Package, Pencil, Plus, Trash2, X } from 'lucide-react-native';
import { API_URL } from '../../utils/userStore';
import { useModal } from '../../components/AppModal';

const GREEN = '#449D3A';
const VACIO: any = { nombre: '', objetivo: '', descripcion: '', contenido: '', costo: '', credencialesIncluidas: '2', maxParticipantes: '2', urlQR: '', orden: '0', nivelMesa: 'NORMAL', tipoParticipacion: 'PRESENCIAL', apareceEnCatalogo: true, logoEnWeb: false, destacadoEnListados: false };
export default function PaquetesScreen({ route }: any) {
  const eventoId = Number(route?.params?.eventoId) || null;
  const [lista, setLista] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [abierto, setAbierto] = useState(false);
  const [editandoId, setEditandoId] = useState<number | null>(null);
  const [guardando, setGuardando] = useState(false);
  const [form, setForm] = useState<any>(VACIO);
  const { show, modal } = useModal();
  const cargar = async () => { setLoading(true); try { const r = await fetch(`${API_URL}/admin/paquetes${eventoId ? `?eventoId=${eventoId}` : ''}`); const d = await r.json(); setLista(r.ok && Array.isArray(d) ? d : []); } finally { setLoading(false); } };
  useEffect(() => { cargar(); }, [eventoId]);
  const nuevo = () => { setEditandoId(null); setForm({ ...VACIO, orden: String(lista.length + 1) }); setAbierto(true); };
  const editar = (p: any) => { setEditandoId(p.id); setForm({ nombre: p.nombre, objetivo: p.objetivo || '', descripcion: p.descripcion || '', contenido: p.contenido || '', costo: String(Number(p.costo)), credencialesIncluidas: String(p.credencialesIncluidas), maxParticipantes: String(p.maxParticipantes || p.credencialesIncluidas), urlQR: p.urlQR || '', orden: String(p.orden || 0), nivelMesa: p.nivelMesa || 'NORMAL', tipoParticipacion: p.tipoParticipacion || 'PRESENCIAL', apareceEnCatalogo: (p.apareceEnCatalogo ?? 1) === 1, logoEnWeb: p.logoEnWeb === 1, destacadoEnListados: p.destacadoEnListados === 1 }); setAbierto(true); };
  const elegirQR = async () => { const permiso = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permiso.granted) return show({ type: 'warning', title: 'Permiso requerido', message: 'Se necesita acceso a las fotos para seleccionar el QR.' }); const r = await ImagePicker.launchImageLibraryAsync({ mediaTypes: 'images', quality: .9 }); if (r.canceled) return; setGuardando(true); try { const fd = new FormData(); fd.append('file', { uri: r.assets[0].uri, name: 'qr.jpg', type: 'image/jpeg' } as any); const res = await fetch(`${API_URL}/admin/imagenes/upload`, { method: 'POST', body: fd }); const d = await res.json(); if (!res.ok || !d.url) throw new Error(d.message || 'No se pudo subir.'); setForm((f: any) => ({ ...f, urlQR: d.url })); } catch (e: any) { show({ type: 'error', title: 'Error al subir', message: e.message }); } finally { setGuardando(false); } };
  const guardar = async () => { if (!form.nombre.trim() || Number(form.costo) < 0 || Number(form.credencialesIncluidas) < 1 || Number(form.maxParticipantes) < Number(form.credencialesIncluidas)) return show({ type: 'warning', title: 'Datos incompletos', message: 'Revisa nombre, costo y cupos. El máximo no puede ser menor a las credenciales incluidas.' }); setGuardando(true); try { const r = await fetch(`${API_URL}/admin/paquetes${editandoId ? `/${editandoId}` : ''}`, { method: editandoId ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, ...(eventoId ? { eventoId } : {}), costo: Number(form.costo), credencialesIncluidas: Number(form.credencialesIncluidas), maxParticipantes: Number(form.maxParticipantes), orden: Number(form.orden) || 0 }) }); const d = await r.json(); if (!r.ok) throw new Error(d.message || 'No se pudo guardar.'); setAbierto(false); await cargar(); show({ type: 'success', title: editandoId ? 'Paquete actualizado' : 'Paquete creado', message: 'Los cambios ya están disponibles en el registro.' }); } catch (e: any) { show({ type: 'error', title: 'No se pudo guardar', message: e.message }); } finally { setGuardando(false); } };
  const eliminar = (p: any) => show({ type: 'confirm', title: 'Eliminar paquete', message: `¿Quitar "${p.nombre}" del formulario?`, onConfirm: async () => { const r = await fetch(`${API_URL}/admin/paquetes/${p.id}`, { method: 'DELETE' }); const d = await r.json(); if (!r.ok) return show({ type: 'error', title: 'No se pudo eliminar', message: d.message || 'Intenta nuevamente.' }); await cargar(); } });
  const campo = (label: string, key: string, props: any = {}) => <View style={{ marginBottom: 11 }}><Text style={{ fontSize: 11, color: '#475569', fontWeight: '800', marginBottom: 5 }}>{label}</Text><TextInput value={form[key]} onChangeText={(v) => setForm((f: any) => ({ ...f, [key]: v }))} style={{ backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 10, padding: 11 }} {...props} /></View>;
  return <View style={{ flex: 1, backgroundColor: '#f8fafc' }}><View style={{ padding: 16, backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#e2e8f0', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><View style={{ flex: 1 }}><Text style={{ fontSize: 21, fontWeight: '900', color: '#0f172a' }}>Paquetes de inscripción</Text><Text style={{ color: '#64748b', fontSize: 12 }}>Sistema oficial de precios y cupos</Text></View><TouchableOpacity onPress={nuevo} style={{ backgroundColor: GREEN, borderRadius: 11, padding: 11 }}><Plus size={20} color="#fff" /></TouchableOpacity></View>
    {loading ? <ActivityIndicator color={GREEN} style={{ marginTop: 45 }} /> : <ScrollView contentContainerStyle={{ padding: 14, gap: 12 }}>{!lista.length ? <Text style={{ color: '#94a3b8', textAlign: 'center', marginTop: 45 }}>Este evento todavía no tiene paquetes. Crea al menos uno antes de activarlo.</Text> : lista.map((p) => <View key={p.id} style={{ backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#e2e8f0', padding: 15 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><View style={{ flex: 1 }}><Text style={{ fontWeight: '900', fontSize: 17, color: '#0f172a' }}>{p.nombre}</Text><Text style={{ color: GREEN, fontSize: 22, fontWeight: '900', marginTop: 6 }}>Bs. {Number(p.costo).toLocaleString('es-BO')}</Text><Text style={{ color: '#64748b', fontSize: 12, marginTop: 5 }}>{p.credencialesIncluidas} credenciales · máximo {p.maxParticipantes} · {p.tipoParticipacion}</Text></View><View style={{ flexDirection: 'row', gap: 7 }}><TouchableOpacity onPress={() => editar(p)} style={{ padding: 8 }}><Pencil size={18} color="#475569" /></TouchableOpacity><TouchableOpacity onPress={() => eliminar(p)} style={{ padding: 8 }}><Trash2 size={18} color="#ef4444" /></TouchableOpacity></View></View>{p.objetivo ? <Text style={{ color: GREEN, fontSize: 12, marginTop: 8 }}>{p.objetivo}</Text> : null}{p.descripcion ? <Text style={{ color: '#475569', fontSize: 12, marginTop: 8 }}>{p.descripcion}</Text> : null}{p.contenido ? <Text style={{ color: '#334155', fontSize: 12, lineHeight: 19, marginTop: 9 }}>{String(p.contenido).split('\n').map((x: string) => `✓ ${x}`).join('\n')}</Text> : null}</View>)}</ScrollView>}
    <Modal visible={abierto} transparent animationType="slide" onRequestClose={() => setAbierto(false)}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={{ flex: 1 }}><View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,.5)', justifyContent: 'flex-end' }}><View style={{ backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '92%' }}><View style={{ padding: 17, borderBottomWidth: 1, borderBottomColor: '#e2e8f0', flexDirection: 'row', justifyContent: 'space-between' }}><Text style={{ fontSize: 18, fontWeight: '900' }}>{editandoId ? 'Editar paquete' : 'Nuevo paquete'}</Text><TouchableOpacity onPress={() => setAbierto(false)}><X size={22} color="#64748b" /></TouchableOpacity></View><ScrollView contentContainerStyle={{ padding: 17 }}>{campo('Nombre *', 'nombre')}{campo('Objetivo', 'objetivo')}{campo('Descripción', 'descripcion', { multiline: true })}{campo('Beneficios (uno por línea)', 'contenido', { multiline: true })}<View style={{ flexDirection: 'row', gap: 9 }}><View style={{ flex: 1 }}>{campo('Costo (Bs.) *', 'costo', { keyboardType: 'numeric' })}</View><View style={{ flex: 1 }}>{campo('Credenciales *', 'credencialesIncluidas', { keyboardType: 'numeric' })}</View></View><View style={{ flexDirection: 'row', gap: 9 }}><View style={{ flex: 1 }}>{campo('Máximo participantes *', 'maxParticipantes', { keyboardType: 'numeric' })}</View><View style={{ flex: 1 }}>{campo('Orden', 'orden', { keyboardType: 'numeric' })}</View></View>
      <Text style={{ fontSize: 11, fontWeight: '800', color: '#475569', marginBottom: 6 }}>Modalidad</Text><View style={{ flexDirection: 'row', gap: 6, marginBottom: 12 }}>{['PRESENCIAL','VIRTUAL','HIBRIDO'].map((v) => <TouchableOpacity key={v} onPress={() => setForm((f: any) => ({ ...f, tipoParticipacion: v }))} style={{ flex: 1, padding: 8, borderRadius: 8, backgroundColor: form.tipoParticipacion === v ? GREEN : '#f1f5f9', alignItems: 'center' }}><Text style={{ fontSize: 9, fontWeight: '800', color: form.tipoParticipacion === v ? '#fff' : '#475569' }}>{v}</Text></TouchableOpacity>)}</View>
      <Text style={{ fontSize: 11, fontWeight: '800', color: '#475569', marginBottom: 6 }}>Nivel de mesa</Text><View style={{ flexDirection: 'row', gap: 6, marginBottom: 12 }}>{['NORMAL','PREFERENCIAL','VIP'].map((v) => <TouchableOpacity key={v} onPress={() => setForm((f: any) => ({ ...f, nivelMesa: v }))} style={{ flex: 1, padding: 8, borderRadius: 8, backgroundColor: form.nivelMesa === v ? GREEN : '#f1f5f9', alignItems: 'center' }}><Text style={{ fontSize: 9, fontWeight: '800', color: form.nivelMesa === v ? '#fff' : '#475569' }}>{v}</Text></TouchableOpacity>)}</View>
      {[['apareceEnCatalogo','Aparece en el catálogo'],['destacadoEnListados','Destacado en listados'],['logoEnWeb','Logo en la web']].map(([key,label]) => <View key={key} style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 7 }}><Text style={{ color: '#334155', fontSize: 12 }}>{label}</Text><Switch value={form[key]} onValueChange={(v) => setForm((f: any) => ({ ...f, [key]: v }))} trackColor={{ true: GREEN }} /></View>)}
      <TouchableOpacity onPress={elegirQR} style={{ borderWidth: 1, borderColor: GREEN, borderRadius: 11, padding: 11, alignItems: 'center', marginVertical: 10 }}><Text style={{ color: GREEN, fontWeight: '800' }}>{form.urlQR ? 'Cambiar QR de pago' : 'Seleccionar QR de pago'}</Text></TouchableOpacity>{form.urlQR ? <Image source={{ uri: form.urlQR }} style={{ width: 100, height: 100, resizeMode: 'contain', alignSelf: 'center' }} /> : null}
      <TouchableOpacity onPress={guardar} disabled={guardando} style={{ backgroundColor: GREEN, borderRadius: 12, padding: 14, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 7, marginTop: 14, opacity: guardando ? .5 : 1 }}>{guardando ? <ActivityIndicator color="#fff" /> : <Check size={18} color="#fff" />}<Text style={{ color: '#fff', fontWeight: '900' }}>{guardando ? 'Guardando...' : 'Guardar paquete'}</Text></TouchableOpacity></ScrollView></View></View></KeyboardAvoidingView></Modal>{modal}</View>;
}
